---
title: "Forecasting: principles and practice"
author: "Rob J Hyndman"
date: "3.3&nbsp; Hierarchical forecasting"
fontsize: 14pt
output:
  beamer_presentation:
    fig_width: 7
    fig_height: 4.3
    highlight: tango
    theme: metropolis
    includes:
      in_header: header.tex
header_includes:
  - \def\bY{\bm{y}}
  - \def\by{\bm{y}}
  - \def\bS{\bm{S}}
  - \def\bI{\text{\rm\textbf{I}}}
  - \def\bbeta{\bm{\beta}}
  - \def\bSigma{\bm{\Sigma}}
  - \def\Var{\text{Var}}
  - \def\var{\text{Var}}
  - \def\bOmega{\bm{\Omega}}
  - \def\bLambda{\bm{\Lambda}}
  - \let\mc\multicolumn
  - \def\hl{\color[RGB]{6,84,182}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  cache=TRUE,
  warning=FALSE,
  message=FALSE)
library(fpp2)
options(digits=4, width=55)
```

# Hierarchical and grouped time series

## Hierarchical and grouped time series

\begin{center}
\begin{minipage}{9.6cm}
\begin{block}{}
\begin{tikzpicture}
\tikzstyle{every node}=[ellipse,draw,inner sep=0.2pt,fill=red!15]
\tikzstyle[level distance=.1cm]
\tikzstyle[sibling distance=7cm]
\tikzstyle{level 1}=[sibling distance=33mm,set style={{every node}+=[fill=blue!15]}]
\tikzstyle{level 2}=[sibling distance=10mm,font=\small,set style={{every node}+=[fill=yellow]}]
\node{Total}[edge from parent fork down]
 child {node {A}
   child {node {AA}}
   child {node {AB}}
   child {node {AC}}
 }
 child {node {B}
   child {node {BA}}
   child {node {BB}}
   child {node {BC}}
 }
 child {node {C}
   child {node {CA}}
   child {node {CB}}
   child {node {CC}}
 };
\end{tikzpicture}
\end{block}
\end{minipage}
\end{center}

\pause

\alert{Examples}

 * Manufacturing product hierarchies
 * Net labour turnover
 * Pharmaceutical sales
 * Tourism demand by region and purpose

## Forecasting the PBS
\full{pills}

## ATC drug classification
\fontsize{13}{13}\sf

\hspace*{-0.5cm}\begin{tabular}{lp{10.7cm}}
A &Alimentary tract and metabolism\\
B &Blood and blood forming organs\\
C &Cardiovascular system\\
D &Dermatologicals\\
G &Genito-urinary system and sex hormones\\
H &Systemic hormonal preparations, excluding sex hormones and insulins\\
J &Anti-infectives for systemic use\\
L &Antineoplastic and immunomodulating agents\\
M &Musculo-skeletal system\\
N &Nervous system\\
P &Antiparasitic products, insecticides and repellents\\
R &Respiratory system\\
S &Sensory organs\\
V &Various
\end{tabular}

## ATC drug classification
\hspace*{-1cm}\begin{minipage}{9.6cm}
\begin{tikzpicture}
\tikzstyle{every node}=[ellipse,font=\small,draw,fill=red!15]
\tikzstyle[level font=\small,set style={{every node}+=[fill=blue!15]}]
\tikzstyle{level 1}=[font=\small,set style={{every node}+=[fill=blue!15]}]
\tikzstyle{level 2}=[font=\small,set style={{every node}+=[fill=yellow]}]
\node[label=right:\hspace*{-0.cm}Alimentary tract and metabolism,label=left:\textbf{14 classes}\hspace*{0.3cm}]{A}[edge from parent fork down]
   child {node[label=right:\hspace*{-0.0cm}Drugs used in diabetes,label=left:\textbf{84 classes}]{A10}
     child {node[label=right:\hspace*{-0.35cm}Blood glucose lowering drugs]{A10B}
       child {node[label=right:\hspace*{0.1cm}Biguanides]{A10BA}
         child {node[label=right:\hspace*{-0.15cm}Metformin]{A10BA02}
 }}}};
 \end{tikzpicture}
\end{minipage}

## Australian tourism
\full{regions1_with_labels}
\only<2>{\begin{textblock}{10}(1,2)
\begin{block}{}
Also split by purpose of travel:
\begin{itemize}
  \item Holiday
  \item Visits to friends and relatives
  \item Business
  \item Other
\end{itemize}
\end{block}
\end{textblock}}

## Hierarchical/grouped time series
\fontsize{13}{15}\sf

 * A \alert{\textbf{hierarchical time series}} is a collection of several time series that are linked together in a hierarchical structure.

\begin{block}{}
\textbf{Example:} Pharmaceutical products are organized in a hierarchy under the Anatomical Therapeutic Chemical (ATC) Classification System.
\end{block}

 * A \alert{\textbf{grouped time series}} is a collection of time series that are aggregated in a number of non-hierarchical ways.

\begin{block}{}
\textbf{Example:} Australian tourism demand is grouped by region and purpose of travel.
\end{block}

## Hierarchical data

\begin{minipage}{4cm}\vspace*{0.2cm}
\begin{block}{}\centering
\begin{tikzpicture}
\tikzstyle{every node}=[ellipse,draw,fill=red!15,inner sep=2pt]
\tikzstyle[level distance=.3cm]
\tikzstyle[sibling distance=12cm]
\tikzstyle{level 1}=[sibling distance=10mm,font=\small,set style={{every node}+=[fill=blue!15]}]
\node{Total}[edge from parent fork down]
 child {node {A}
 }
 child {node {B}
 }
 child {node {C}
 };
\end{tikzpicture}
\end{block}
\end{minipage}

\only<2->{\begin{textblock}{6.3}(6,1)\small
\begin{itemize}\itemsep=0cm\parskip=0cm
\item[ $ Y_{t}: $] observed aggregate of all series at time
$t$.
\item[ $ Y_{X,t}: $] observation on series $X$ at time $t$.
\item[ $ \bm{B}_{t}: $] vector of all series at bottom level
in time $t$.
\end{itemize}
\end{textblock}}\vspace*{0.6cm}
\only<3->{
$\bY_{t}= [Y_{t},Y_{A,t},Y_{B,t},Y_{C,t}]' = \only<3>{\hspace*{0.01cm}\begin{pmatrix}
                1 & 1 & 1 \\
                1 & 0 & 0 \\
                0 & 1 & 0\\
                0 & 0 & 1
                \end{pmatrix}}\only<4->{{\color{red}\underbrace{\begin{pmatrix}
                1 & 1 & 1 \\
                1 & 0 & 0 \\
                0 & 1 & 0\\
                0 & 0 & 1
                \end{pmatrix}}_{\bS}}}\only<3>{\hspace*{0.08cm}}\only<3>{\hspace*{-0.1cm}\begin{pmatrix}Y_{A,t}\\Y_{B,t}\\Y_{C,t}\end{pmatrix}}\rule{0cm}{1.6cm}
                \only<4->{\hspace*{0.08cm}{\color{blue}\underbrace{\begin{pmatrix}Y_{A,t}\\Y_{B,t}\\Y_{C,t}\end{pmatrix}}_{\bm{B}_{t}}}}$}

\vspace*{-0.6cm}

\only<4>{\colorbox[gray]{.8}{$\bY_{t}=\color{red}\bS\color{blue}\bm{B}_{t}$}}

\vspace*{10cm}

## Hierarchical data

\begin{block}{}\hspace*{.6cm}{\centering\small
\begin{tikzpicture}[level distance=1cm]
\tikzstyle{every node}=[ellipse,draw,fill=red!15,inner sep=2pt]
\tikzstyle[level distance=.01cm]
\tikzstyle[sibling distance=12cm]
\tikzstyle{level 2}=[sibling distance=10mm,font=\scriptsize,set style={{every node}+=[fill=yellow]}]
\tikzstyle{level 1}=[sibling distance=40mm,font=\footnotesize,set style={{every node}+=[fill=blue!15]}]
\node{Total}[edge from parent fork down]
 child {node {A}
   child {node {AX}}
   child {node {AY}}
   child {node {AZ}}
 }
 child {node {B}
   child {node {BX}}
   child {node {BY}}
   child {node {BZ}}
 }
 child {node {C}
   child {node {CX}}
   child {node {CY}}
   child {node {CZ}}
 };
\end{tikzpicture}}
\end{block}\vspace*{0.1cm}\pause\fontsize{13}{15}\sf

\hbox{$\bY_{t}= {\scriptsize\begin{pmatrix}
    Y_t\\
    Y_{A,t}\\
    Y_{B,t}\\
    Y_{C,t}\\
    Y_{AX,t}\\
    Y_{AY,t}\\
    Y_{AZ,t}\\
    Y_{BX,t}\\
    Y_{BY,t}\\
    Y_{BZ,t}\\
    Y_{CX,t}\\
    Y_{CY,t}\\
    Y_{CZ,t}\end{pmatrix}}=
    {\color{red}\underbrace{\scriptsize\begin{pmatrix}
                1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1\\
                1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0\\
                0 & 0 & 0 & 1 & 1 & 1 & 0 & 0 & 0\\
                0 & 0 & 0 & 0 & 0 & 0 & 1 & 1 & 1\\
                1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
                0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
                0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 0\\
                0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0\\
                0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0\\
                0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0\\
                0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0\\
                0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0\\
                0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\
             \end{pmatrix}}_{\bS}}{\color{blue}\underbrace{\scriptsize\begin{pmatrix}
    Y_{AX,t}\\
    Y_{AY,t}\\
    Y_{AZ,t}\\
    Y_{BX,t}\\
    Y_{BY,t}\\
    Y_{BZ,t}\\
    Y_{CX,t}\\
    Y_{CY,t}\\
    Y_{CZ,t}\end{pmatrix}}_{\bm{B}_{t}}}$}

    \vspace*{10cm}

\only<3>{\begin{textblock}{3}(10.5,8)\colorbox[gray]{.8}{$\bY_{t}=\color{red}\bS\color{blue}\bm{B}_{t}$}\end{textblock}}

## Grouped data

\begin{block}{}
\begin{center}\small
\tikzstyle{every node}=[inner sep=2pt]
\begin{tikzpicture}
    \matrix[ampersand replacement=\&,column sep=0.3cm] {
        \node[ellipse,draw,fill=yellow,font=\scriptsize,distance=1cm] {AX};~ \&
        \node[ellipse,draw,fill=yellow,font=\scriptsize] {AY};~ \&
        \node[ellipse,draw,fill=blue!15] {A}; \\[0.3cm]
        \node[ellipse,draw,fill=yellow,font=\scriptsize] {BX};~ \&
        \node[ellipse,draw,fill=yellow,font=\scriptsize] {BY};~ \&
        \node[ellipse,draw,fill=blue!15] {B}; \\[0.3cm]
        \node[ellipse,draw,fill=blue!15] {X};~ \&
        \node[ellipse,draw,fill=blue!15] {Y};~ \&
        \node[ellipse,draw,fill=red!15] {Total}; \\
};
\end{tikzpicture}
\end{center}
\end{block}\vspace*{0.0cm}\pause\fontsize{13}{14}\sf

\hbox{$\bY_{t}= {\small\begin{pmatrix}
    Y_t\\
    Y_{A,t}\\
    Y_{B,t}\\
    Y_{X,t}\\
    Y_{Y,t}\\
    Y_{AX,t}\\
    Y_{AY,t}\\
    Y_{BX,t}\\
    Y_{BY,t}
    \end{pmatrix}}=
    \color{red}\underbrace{\small\begin{pmatrix}
                1 & 1 & 1 & 1 \\
                1 & 1 & 0 & 0 \\
                0 & 0 & 1 & 1 \\
                1 & 0 & 1 & 0 \\
                0 & 1 & 0 & 1 \\
                1 & 0 & 0 & 0 \\
                0 & 1 & 0 & 0 \\
                0 & 0 & 1 & 0 \\
                0 & 0 & 0 & 1
             \end{pmatrix}}_{\bS} \color{blue}\underbrace{\small\begin{pmatrix}
    Y_{AX,t}\\
    Y_{AY,t}\\
    Y_{BX,t}\\
    Y_{BY,t}
    \end{pmatrix}}_{\bm{B}_{t}}$}

\vspace*{-1cm}

\only<3>{\begin{textblock}{3}(10.5,8)\colorbox[gray]{.8}{$\bY_{t}=\color{red}\bS\color{blue}\bm{B}_{t}$}\end{textblock}}


# Forecasting framework

## Forecasting notation

Let $\hat{\bY}_n(h)$ be vector of initial $h$-step forecasts, made at time $n$, stacked in same order as $\bY_t$. \pause  (They may not add up.)\pause

\begin{block}{}
Hierarchical forecasting methods of the form:

\centerline{$ \tilde{\bY}_{n}(h)=\bS\bm{P}\hat{\bY}_{n}(h)$}

for some matrix $\bm{P}$.
\end{block}\pause

 * $\bm{P}$ extracts and combines base forecasts $\hat{\bY}_{n}(h)$ to get bottom-level forecasts.
 * $\bS$ adds them up
 * Revised reconciled forecasts: $\tilde{\bY}_{n}(h)$.

## Bottom-up forecasts

\begin{alertblock}{}
\centerline{$ \tilde{\bY}_{n}(h)=\bS\bm{P}\hat{\bY}_{n}(h)$}
\end{alertblock}\pause

Bottom-up forecasts are obtained using
\[
\bm{P} = \left[\bm{0}\mid \bI\right],
\]
where $\bm{0}$ is null matrix and $\bI$ is identity matrix.

* $\bm{P}$ matrix extracts only bottom-level forecasts from $\hat{\bY}_{n}(h)$
* $\bS$ adds them up to give the bottom-up forecasts.

## Top-down forecasts

\begin{alertblock}{}
\centerline{$ \tilde{\bY}_{n}(h)=\bS\bm{P}\hat{\bY}_{n}(h)$}
\end{alertblock}\pause

Top-down forecasts are obtained using
\[
\bm{P}= \left[\bm{p}\mid\bm{0}\right]
\]
where $\bm{p}=[p_{1},p_{2},\dots,p_{m_{K}}]'$ is a vector of proportions that sum to one.

 * $\bm{P}$ distributes forecasts of the aggregate to the lowest level series.
 * Different methods of top-down forecasting lead to different proportionality vectors $\bm{p}$.

## General properties: bias and variance

\begin{block}{}
\centerline{$ \tilde{\bY}_{n}(h)=\bS\bm{P}\hat{\bY}_{n}(h)$}
\end{block}\pause

\textbf{\alert{Bias}}
\begin{alertblock}{}\centering
Reconciled forecasts are unbiased iff $\bS\bm{P}\bS=\bS$.\rlap{\phantom{g}}
\end{alertblock}\pause

\textbf{\alert{Variance}}\newline
Let error variance of $h$-step base forecasts $\hat{\by}_n(h)$ be
$$\bSigma_h = \var[\by_{n+h} - \hat{\by}_{n}(h) \mid \by_1,\dots,\by_n] $$
Then error variance of the reconciled forecasts is
\begin{alertblock}{}
\centerline{$\var[\by_{n+h} - \tilde{\by}_{n}(h)  \mid \by_1,\dots,\by_n]  = \bS\bm{P}\bSigma_{h}\bm{P}'\bS'$}
\end{alertblock}

## Optimal forecast reconciliation
\begin{block}{}
\centerline{$ \tilde{\by}_{n}(h)=\bS\bm{P}\hat{\by}_{n}(h)$}
\end{block}\pause\vspace*{0.4cm}

\begin{alertblock}{Theorem: MinT Reconciliation}
If $\bm{P}$ satisfies $\bm{S}\bm{P}\bm{S} = \bm{S}$,  then

\centerline{$\min_{\bm{P}} = \text{trace}[\bm{S}\bm{P}\bSigma_h\bm{P}'\bm{S}']$}

has solution $\bm{P} = (\bS'\bSigma^{-1}_{h}\bS)^{-1}\bS'\bSigma^{-1}_{h}$.
\end{alertblock}\pause

\only<3->{
\begin{textblock}{8}(2.4,6)
\begin{block}{}
\centerline{$\displaystyle\tilde{\by}_{n}(h) =\bS(\bS'\bSigma^{-1}_{h}\bS)^{-1}\bS'\bSigma^{-1}_{h} \hat{\by}_{n}(h)$}
\end{block}\end{textblock}}\vspace*{1.3cm}


\vspace*{10cm}

## Optimal forecast reconciliation


\begin{textblock}{8}(2.4,1.4)
\begin{block}{}
\centerline{$\displaystyle\tilde{\by}_{n}(h) =\bS(\bS'\bSigma^{-1}_{h}\bS)^{-1}\bS'\bSigma^{-1}_{h} \hat{\by}_{n}(h)$}
\end{block}\end{textblock}\vspace*{1.3cm}


Assume that $\bSigma_h =k_h \bSigma_1$ to simplify computations.

\pause

\begin{block}{WLS solution}
\begin{itemize}
\item Approximate $\bSigma_1$ by its diagonal.
\end{itemize}
\end{block}

\pause

\begin{block}{GLS solution}
\begin{itemize}
\item Estimate $\bSigma_1$ using shrinkage to the diagonal.
\end{itemize}
\end{block}

\vspace*{10cm}

## Features
\fontsize{15}{17}\sf

 * Covariates can be included in initial forecasts.
 * Adjustments can be made to initial forecasts at any level.
 * Very simple and flexible method. Can work with \textit{any} hierarchical or grouped time series.
 * Conceptually easy to implement: regression of base forecasts on structure matrix.
 * Weights are independent of the data and of the covariance structure of the hierarchy.

# Application: Australian tourism

## Australian tourism
\full{regions1_with_labels}
\only<3-4>{\begin{textblock}{6.8}(2,2)
\begin{block}{Hierarchy:}
  \begin{itemize}
      \item  States (7)
      \item  Zones (27)
      \item  Regions (82)
  \end{itemize}
\end{block}
\end{textblock}}
\only<4>{\begin{textblock}{6.8}(2,6)
\begin{block}{Base forecasts}
ETS (exponential smoothing) models
\end{block}\end{textblock}}

\only<2>{\begin{textblock}{10.}(1.4,2)
\begin{block}{Domestic visitor nights}
Quarterly data: 1998 -- 2006.\\
From: \textit{National Visitor Survey}, based on annual interviews of 120,000 Australians aged 15+, collected by Tourism Research Australia.
\end{block}
\end{textblock}}


## Base forecasts
\only<1>{\full{austourism1}}
\only<2>{\full{austourism2}}
\only<3>{\full{austourism3}}
\only<4>{\full{austourism4}}
\only<5>{\full{austourism5}}
\only<6>{\full{austourism6}}
\only<7>{\full{austourism7}}
\only<8>{\full{austourism8}}
\only<9>{\full{austourism9}}

## Reconciled forecasts
\only<1>{\full{Australia}}
\only<2>{\full{States}}
\only<3>{\full{Capitals}}

## Forecast evaluation

  * Select models using all observations;
  * Re-estimate models using first 12 observations and generate 1- to 8-step-ahead forecasts;
  * Increase sample size one observation at a time, re-estimate models, generate forecasts until the end of the sample;
  * In total 24 1-step-ahead, 23 2-steps-ahead, up to 17 8-steps-ahead for forecast evaluation.

## Hierarchy: states, zones, regions
\fontsize{10}{10.5}\sf\tabcolsep=0.12cm\vspace*{-0.6cm}
\hspace*{-0.2cm}\begin{tabular}{lrrrrrrr}
            & \multicolumn{6}{c}{\bf Forecast horizon} & \\
\textbf{RMSE} & $h=1$  & $h=2$ & $h=3$ & $h=4$ & $h=5$ & $h=6$ & \textbf{Ave}\\
\midrule
\multicolumn{8}{c}{\bf\alert{Australia}}\\
Base   & 1762.04    & 1770.29    & 1766.02     & 1818.82    & 1705.35    & 1721.17    & \bf 1757.28 \\
Bottom & 1736.92    & 1742.69    & 1722.79     & 1752.74    & 1666.73    & 1687.43    & \bf 1718.22 \\
WLS    & 1705.21    & 1715.87    & \hl 1703.75 & 1729.56    & 1627.79    & \hl1661.24 & \bf 1690.57 \\
GLS    & \hl1704.64 & \hl1715.60 & 1705.31     & \hl1729.04 & \hl1626.36 & 1661.64    & \bf \hl 1690.43 \\[0.1cm]
\multicolumn{8}{c}{\bf\alert{States}}\\
Base   & 399.77     & 404.16     & 401.92      & 407.26     & 395.38     & 401.17     & \bf 401.61 \\
Bottom & 404.29     & 406.95     & 404.96      & 409.02     & 399.80     & 401.55     & \bf 404.43 \\
WLS    & \hl 398.84 & \hl 402.12 & \hl 400.71  & \hl 405.03 & 394.76     & 398.23     & \bf \hl 399.95 \\
GLS    & \hl 398.84 & 402.16     & 400.86      & \hl 405.03 & \hl 394.59 & \hl 398.22 & \bf \hl 399.95 \\[0.1cm]
\multicolumn{8}{c}{\bf\alert{Regions}}\\
Base   & 93.15      & 93.38      & 93.45       & 93.79      & 93.50      & 93.56      & \bf 93.47 \\
Bottom & 93.15      & 93.38      & 93.45       & 93.79      & 93.50      & 93.56      & \bf 93.47 \\
WLS    & 93.02      & 93.32      & 93.38       & 93.72      & 93.39      & 93.53      & \bf 93.39 \\
GLS    & \hl 92.98  & \hl 93.27  & \hl 93.34   & \hl 93.66  & \hl 93.34  & \hl 93.46  & \bf \hl 93.34
\end{tabular}



# hts package for R

## hts package for R
\placefig{9.5}{1}{width=2cm}{Rlogo}

\begin{textblock}{12.}(0.5,1.7)\fontsize{11}{14}\sf
\alert{hts: Hierarchical and grouped time series}

Methods for analysing and forecasting hierarchical and grouped time series\vspace*{0.3cm}

\tabcolsep=0.1cm
\begin{tabular}{@{}ll}
Version: & 5.1.5\\
Depends: & R ($\ge 3.2.0$), forecast ($\ge 8.1$)\\
Published: & 2018-03-26\\
Author: & Rob J Hyndman, Earo Wang, Shanika Wickramasuriya, Alan Lee\\
Maintainer: & Earo Wang $<$Earo.Wang at monash.edu$>$\\
BugReports: & \url{https://github.com/earowang/hts/issues} \\
License: & GPL ($\ge2$) \\
URL: & \url{http://pkg.earo.me/hts}
\end{tabular}
\end{textblock}

## Example using R
\fontsize{10}{10}\sf

```r
library(hts)

# bts is a matrix containing the bottom level time series
# nodes describes the hierarchical structure
y <- hts(bts, nodes=list(2, c(3,2)))
```

\only<2>{\begin{textblock}{5}(7,3.5){\begin{block}{}\centering\small
\begin{tikzpicture}[level distance=1cm]
\tikzstyle{every node}=[ellipse,draw,fill=red!15,inner sep=2pt]
\tikzstyle[level distance=.01cm]
\tikzstyle[sibling distance=4cm]
\tikzstyle{level 2}=[sibling distance=10mm,font=\scriptsize,set style={{every node}+=[fill=yellow]}]
\tikzstyle{level 1}=[sibling distance=30mm,font=\footnotesize,set style={{every node}+=[fill=blue!15]}]
\node{Total}[edge from parent fork down]
 child {node {A}
   child {node {AX}}
   child {node {AY}}
   child {node {AZ}}
 }
 child {node {B}
   child {node {BX}}
   child {node {BY}}
 };
\end{tikzpicture}\end{block}}\end{textblock}}

\vspace*{10cm}

## Example using R
\fontsize{10}{10}\sf

```r
library(hts)

# bts is a matrix containing the bottom level time series
# nodes describes the hierarchical structure
y <- hts(bts, nodes=list(2, c(3,2)))
```

\begin{textblock}{5}(7,3.5){\begin{block}{}\centering\small
\begin{tikzpicture}[level distance=1cm]
\tikzstyle{every node}=[ellipse,draw,fill=red!15,inner sep=2pt]
\tikzstyle[level distance=.01cm]
\tikzstyle[sibling distance=4cm]
\tikzstyle{level 2}=[sibling distance=10mm,font=\scriptsize,set style={{every node}+=[fill=yellow]}]
\tikzstyle{level 1}=[sibling distance=30mm,font=\footnotesize,set style={{every node}+=[fill=blue!15]}]
\node{Total}[edge from parent fork down]
 child {node {A}
   child {node {AX}}
   child {node {AY}}
   child {node {AZ}}
 }
 child {node {B}
   child {node {BX}}
   child {node {BY}}
 };
\end{tikzpicture}\end{block}}\end{textblock}

\vspace*{3.4cm}

```r
# Forecast 10-step-ahead using WLS combination method
# ETS used for each series by default
fc <- forecast(y, h=10)
```

\vspace*{10cm}

## forecast.gts() function
\fontsize{10}{10}\sf

\alert{Usage}

```r
forecast(object, h,
  method = c("comb", "bu", "mo", "tdgsf", "tdgsa", "tdfp"),
  fmethod = c("ets", "rw", "arima"),
  weights = c("wls", "ols", "minmt", "nseries"),
  covariance = c("shr","sam"),
  positive = TRUE,
  parallel = FALSE, num.cores = 2, ...)
```

\vspace*{-0.2cm}

\alert{Arguments}\vspace*{-0.2cm}

\begin{tabular}{lp{9.4cm}}
\Verb|object| & Hierarchical time series object of class \texttt{gts}.\\
\Verb|h| & Forecast horizon\\
\Verb|method| & Method for distributing forecasts within the hierarchy. \\
\Verb|fmethod| & Forecasting method to use\\
\Verb|positive| & If TRUE, forecasts are forced to be strictly positive\\
\Verb|weights| & Weights used for "optimal combination" method. \\
\Verb|parallel| & If TRUE, allow parallel processing\\
\Verb|num.cores| & If parallel = TRUE, specify how many cores are going to be used
\end{tabular}

\vspace*{4cm}

